### ISSUE TITLE
Parallelism checklist

### ISSUE THREAD

**Issue by sjboeing** [EPIC-model/epic#335]
- [x] Set up basic MPI and parallel reading of configuration
- [x] Set up domain decomposition and halo regions (see #361)
- [x] Extend NetCDF to parallel I/O (see  #363). If having single files for parcels gives us issues, we could still try a file-per-node strategy.
- [x] Read and write parcels in parallel (see #365)
- [x] Read and write grid from/t0 file (parallel IO) (see #367)
- [x] Initialise parcels from grid *(unit test: test_parcel_init.f90)* (see #373)
- [x] Field and parcel diagnostics (see #368)
- [x] #449
- [x] #371 (see #377)
- [x] Implement grid halo swap (see #369)
- [x] Implement parcel halo swap (see #362)
- [x] Change blocking to non-blocking communication in parcel and field halo swaps to avoid deadlocks with large messages (fixed in #373 and in #376)
- [x] Implement parallel par2grid (related to parcel intialisation) *(unit test: test_trilinear.f90)* (see  #374)
- [x] Implement parallel grid2par *(unit test: test_grid2par.f90)* (see  #375)
- [x] Implement solver and FFTs in parallel *(unit tests: test_fft_3d.f90, test_fft_2_3d.f90, test_vor2vel.f90, test_lapinv0_1.f90, test_lapinv0_2.f90, test_diffz0.f90, test_diffz1.f90, test_velgradg.f90)* (see #428)
- [x] Implement parcel corrections in parallel *(unit test: test_parcel_correction_3d.f90)*:
    - [x] gradient correction *(unit test: test_gradient_correction_3d.f90)* (see  #383)
    - [x] Laplace correction *(unit test: test_laplace_correction_3d.f90)* (see  #442)
- [x] Extend timer module to MPI (see #443)
- [x] Implement splitting with haloswap *(unit test: test_ellipsoid_split.f90)* (see #376)
- [x] Implement parallel merging (see  #384)
    - [x] transfer of small parcels for nearest neighbour check
    - [x] nearest neighbour check on each memory domain
    - [x] selecting the correct nearest neighbour across domains
    - [x] establish the merging dual tree
    - [x] resolve the merging dual tree
    - [x] ~perform merges *(unit tests: test_ellipsoid_merge_1.f90, test_ellipsoid_merge_2.f90)*~

**Comment by matt-frey** [comment]
I close this issue as all tasks are done.
